# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-PidSimple
version:      0.05
version_from: lib/File/PidSimple.pm
installdirs:  site
requires:
    Carp:                          0
    File::Basename:                0
    File::Spec:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
